min_os_version: 1.3.8
name: AI提示词优化器
package: cloud.lazycat.app.prompt-optimizer
version: 2.2.1
description: 一个好用的提示词优化工具，帮助你优化和测试AI提示词
homepage: https://github.com/linshenkx/prompt-optimizer
author: linshenkx
application:
  subdomain: prompt-optimizer
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://prompt-optimizer:80/

    - location: /mcp
      backend: http://prompt-optimizer:3000/

services:
  prompt-optimizer:
    # linshen/prompt-optimizer:2.2.1
    image: registry.lazycat.cloud/czyt/linshen/prompt-optimizer:64974b8fdfbb4946
    container_name: prompt-optimizer

    environment:
      # nginx内部端口配置
      - NGINX_PORT=${NGINX_PORT:-80}

      # Web应用API配置
      - VITE_OPENAI_API_KEY={{.U.openai_apikey}}
      - VITE_GEMINI_API_KEY={{.U.gemini_apikey}}
      - VITE_DEEPSEEK_API_KEY={{.U.deepseek_apikey}}
      - VITE_SILICONFLOW_API_KEY={{.U.siliconflow_apikey}}
      - VITE_ZHIPU_API_KEY={{.U.zhipu_apikey}}
      - VITE_CUSTOM_API_KEY={{.U.custom_apikey}}
      - VITE_CUSTOM_API_BASE_URL={{.U.custom_api_base_url}}
      - VITE_CUSTOM_API_MODEL= {{.U.custom_api_model}}
      # MCP服务器配置（Docker内部固定端口3000，不使用MCP_HTTP_PORT）
      # - MCP_HTTP_PORT=${MCP_HTTP_PORT:-3000}  # Docker中固定使用3000端口
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL:-debug}
      - MCP_DEFAULT_LANGUAGE={{.U.mcp_default_language}}
      - MCP_DEFAULT_MODEL_PROVIDER={{.U.mcp_default_model_provider}}

      # Basic认证配置（可选）
      - ACCESS_USERNAME={{.U.access_username}}
      - ACCESS_PASSWORD={{.U.access_password}}

locales:
  zh:
    name: "AI提示词优化器"
    description: "一个好用的提示词优化工具，帮助你优化和测试AI提示词"
  en:
    name: "Prompt Optimizer"
    description: "A powerful AI prompt optimization tool that helps you write better AI prompts and improve the quality of AI outputs"
